// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPFOukzUE2BN-bxZmm22A2W7sjrhdAyyQ',
    appId: '1:668764689770:android:df17bc321edeb6ab758113',
    messagingSenderId: '668764689770',
    projectId: 'my-library-a2671',
    storageBucket: 'my-library-a2671.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD50Gotsjo89DUW3KmzuLli_Q6dSx-J9nA',
    appId: '1:668764689770:ios:697ff1bc770e8376758113',
    messagingSenderId: '668764689770',
    projectId: 'my-library-a2671',
    storageBucket: 'my-library-a2671.firebasestorage.app',
    androidClientId: '668764689770-8g5a04jfkgk9rds4nqut5as96e2htg3t.apps.googleusercontent.com',
    iosClientId: '668764689770-jcveo8mvo1rhhdhtuivb9qoatag6cksc.apps.googleusercontent.com',
    iosBundleId: 'com.dss.library',
  );

}